    const dataset = [
        { APPLICATION_ID: 1, AWARD_NOTICE_DATE: "2020-01-01", FY: 2020, IC_NAME: "JESSE BROWN VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "New York", ORG_COUNTRY: "USA", ORG_DEPT: "Dept A", ORG_NAME: "JESSE BROWN VA MEDICAL CENTER", PHR: "PHR A", PROJECT_TERMS: "Term A", PROJECT_TITLE: "Title A", DIRECT_COST_AMT: 50000, INDIRECT_COST_AMT: 10000, TOTAL_COST: 60000 },
        { APPLICATION_ID: 2, AWARD_NOTICE_DATE: "2020-01-01", FY: 2020, IC_NAME: "CLEMENT J. ZABLOCKI VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Chicago", ORG_COUNTRY: "USA", ORG_DEPT: "Dept B", ORG_NAME: "VETERANS HEALTH ADMINISTRATION", PHR: "PHR B", PROJECT_TERMS: "Term B", PROJECT_TITLE: "Title B", DIRECT_COST_AMT: 80000, INDIRECT_COST_AMT: 20000, TOTAL_COST: 100000 },
        // Add more records as needed
        { APPLICATION_ID: 3, AWARD_NOTICE_DATE: "2020-01-01", FY: 2020, IC_NAME: "PROVIDENCE VA  MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Los Angeles", ORG_COUNTRY: "USA", ORG_DEPT: "Dept C", ORG_NAME: "DURHAM VA MEDICAL CENTER", PHR: "PHR C", PROJECT_TERMS: "Term C", PROJECT_TITLE: "Title C", DIRECT_COST_AMT: 30000, INDIRECT_COST_AMT: 15000, TOTAL_COST: 45000 },
        { APPLICATION_ID: 4, AWARD_NOTICE_DATE: "2020-01-01", FY: 2020, IC_NAME: "ELORAC, INC.", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "CAN", ORG_DEPT: "Dept D", ORG_NAME: "UNIVERSITY OF TORONTO", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 5, AWARD_NOTICE_DATE: "2020-03-01", FY: 2020, IC_NAME: "JESSE BROWN VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "AUT", ORG_DEPT: "Dept D", ORG_NAME: "TUWIEN", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 6, AWARD_NOTICE_DATE: "2020-03-01", FY: 2020, IC_NAME: "MINNEAPOLIS VA  MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "TUR", ORG_DEPT: "Dept D", ORG_NAME: "qweqw", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 7, AWARD_NOTICE_DATE: "2020-03-01", FY: 2020, IC_NAME: "MINNEAPOLIS VA  MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "DEU", ORG_DEPT: "Dept D", ORG_NAME: "dwqdq", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 8, AWARD_NOTICE_DATE: "2020-03-01", FY: 2020, IC_NAME: "EDWARD HINES JR VA HOSPITAL", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "FRA", ORG_DEPT: "Dept D", ORG_NAME: "fg", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 9, AWARD_NOTICE_DATE: "2019-03-01", FY: 2019, IC_NAME: "PORTLAND VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "BRA", ORG_DEPT: "Dept D", ORG_NAME: "er", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 10, AWARD_NOTICE_DATE: "2023-03-01", FY: 2023, IC_NAME: "VA PUGET SOUND HEALTHCARE SYSTEM", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "MEX", ORG_DEPT: "Dept D", ORG_NAME: "TUWgfdgIEN", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 11, AWARD_NOTICE_DATE: "2022-03-01", FY: 2022, IC_NAME: "DURHAM VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "RUS", ORG_DEPT: "Dept D", ORG_NAME: "dfg", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 12, AWARD_NOTICE_DATE: "2021-03-01", FY: 2021, IC_NAME: "MICHAEL E DEBAKEY VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "RUS", ORG_DEPT: "Dept D", ORG_NAME: "TUcvbWIEN", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 50000 },
        { APPLICATION_ID: 12, AWARD_NOTICE_DATE: "2021-03-01", FY: 2021, IC_NAME: "MICHAEL E DEBAKEY VA MEDICAL CENTER", NIH_SPENDING_CATS: "Research", ORG_CITY: "Toronto", ORG_COUNTRY: "RUS", ORG_DEPT: "Dept D", ORG_NAME: "TUcvbWIEN", PHR: "PHR D", PROJECT_TERMS: "Term D", PROJECT_TITLE: "Title D", DIRECT_COST_AMT: 45000, INDIRECT_COST_AMT: 5000, TOTAL_COST: 30000 }
    ];

    const worldData = {
        USA: { fundedAvg: 70, countryName: "United States" },
        CAN: { fundedAvg: 50, countryName: "Canada" },
        AUT: { fundedAvg: 80, countryName: "Austria" },
        GER: { fundedAvg: 100, countryName: "Germany" },
        FRA: { fundedAvg: 80, countryName: "France" },
        TUR: { fundedAvg: 80, countryName: "Turkey" },
        BRA: { fundedAvg: 80, countryName: "Brazil" },
        MEX: { fundedAvg: 80, countryName: "Mexico" },
        RUS: { fundedAvg: 80, countryName: "Russia" },
        IND: { fundedAvg: 80, countryName: "India" }
        
    };
